'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.1433
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace ServiceReference1
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0"),  _
     System.Runtime.Serialization.CollectionDataContractAttribute(Name:="ArrayOfInt", [Namespace]:="http://tempuri.org/", ItemName:="int"),  _
     System.SerializableAttribute()>  _
    Public Class ArrayOfInt
        Inherits System.Collections.Generic.List(Of Integer)
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="ServiceReference1.ServiceSoap")>  _
    Public Interface ServiceSoap
        
        'CODEGEN: Generating message contract since element name FactorsOfNoResult from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/FactorsOfNo", ReplyAction:="*")>  _
        Function FactorsOfNo(ByVal request As ServiceReference1.FactorsOfNoRequest) As ServiceReference1.FactorsOfNoResponse
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class FactorsOfNoRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="FactorsOfNo", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As ServiceReference1.FactorsOfNoRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ServiceReference1.FactorsOfNoRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class FactorsOfNoRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public no As Integer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal no As Integer)
            MyBase.New
            Me.no = no
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class FactorsOfNoResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="FactorsOfNoResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As ServiceReference1.FactorsOfNoResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ServiceReference1.FactorsOfNoResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class FactorsOfNoResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public FactorsOfNoResult As ServiceReference1.ArrayOfInt
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal FactorsOfNoResult As ServiceReference1.ArrayOfInt)
            MyBase.New
            Me.FactorsOfNoResult = FactorsOfNoResult
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")>  _
    Public Interface ServiceSoapChannel
        Inherits ServiceReference1.ServiceSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")>  _
    Partial Public Class ServiceSoapClient
        Inherits System.ServiceModel.ClientBase(Of ServiceReference1.ServiceSoap)
        Implements ServiceReference1.ServiceSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceReference1_ServiceSoap_FactorsOfNo(ByVal request As ServiceReference1.FactorsOfNoRequest) As ServiceReference1.FactorsOfNoResponse Implements ServiceReference1.ServiceSoap.FactorsOfNo
            Return MyBase.Channel.FactorsOfNo(request)
        End Function
        
        Public Function FactorsOfNo(ByVal no As Integer) As ServiceReference1.ArrayOfInt
            Dim inValue As ServiceReference1.FactorsOfNoRequest = New ServiceReference1.FactorsOfNoRequest
            inValue.Body = New ServiceReference1.FactorsOfNoRequestBody
            inValue.Body.no = no
            Dim retVal As ServiceReference1.FactorsOfNoResponse = CType(Me,ServiceReference1.ServiceSoap).FactorsOfNo(inValue)
            Return retVal.Body.FactorsOfNoResult
        End Function
    End Class
End Namespace
