create table PATIENT_treatment(
  PATIENT_ID NUMBER(5),
  TREATMENT_ID NUMBER(5),
  APPOINTMENT_DATE DATE,
   PRIMARY KEY (PATIENT_ID,TREATMENT_ID),
  FOREIGN KEY(PATIENT_ID) REFERENCES PATIENT(PATIENT_ID) ON DELETE CASCADE,
  FOREIGN KEY(TREATMENT_ID) REFERENCES TREATMENT(TREATMENT_ID) ON DELETE CASCADE
);