CREATE OR REPLACE PACKAGE BODY MATH_PACK IS
  
  FUNCTION EVENODD(N NUMBER) RETURN VARCHAR2 IS
  BEGIN
    IF((N MOD 2)=0) THEN
      RETURN ('EVEN');
    ELSE
      RETURN('ODD');
    END IF;
  END;
  
END MATH_PACK;   