CREATE OR REPLACE PACKAGE BODY PIECE_PACK IS
  COSTP NUMBER; 
  BNAME VARCHAR2(80);
  
  CURSOR C1 IS SELECT * FROM PIECE;
  C_ROW C1 %ROWTYPE;
   
 PROCEDURE TO_DISPLAY IS
   BEGIN
    FOR C_ROW IN C1 LOOP
      DBMS_OUTPUT.PUT_LINE('----------------------------------------------');
      DBMS_OUTPUT.PUT_LINE('PIECE ID IS: ' ||C_ROW.PIECE_ID);
      DBMS_OUTPUT.PUT_LINE('PIECE NAME IS: ' ||C_ROW.PIECE_NAME);
      DBMS_OUTPUT.PUT_LINE('PIECE COST IS: ' ||C_ROW.PIECE_COST);
      DBMS_OUTPUT.PUT_LINE('ARTIST ID IS: ' ||C_ROW.ARTIST_ID);
      DBMS_OUTPUT.PUT_LINE('BUYER ID IS: ' ||C_ROW.BUYER_ID);
      DBMS_OUTPUT.PUT_LINE('BOUGHT ON: ' ||C_ROW.BOUGHT_ON);
      DBMS_OUTPUT.PUT_LINE('----------------------------------------------');
    END LOOP;
  END TO_DISPLAY;
  
  FUNCTION EXP_PIECE RETURN NUMBER IS
  BEGIN
     SELECT MAX(PIECE_COST) INTO COSTP 
     FROM PIECE;
     RETURN(COSTP);
   END EXP_PIECE;
  FUNCTION NAME(PID NUMBER) RETURN VARCHAR2 IS
  BEGIN 
    SELECT BUY_FIRST_NAME||' '||BUY_LAST_NAME INTO BNAME  
    FROM BUYER B,PIECE P
    WHERE B.BUYER_ID=P.BUYER_ID AND P.PIECE_ID=PID;
    RETURN (BNAME);
  END;
END PIECE_PACK; 
      
      