CREATE OR REPLACE PACKAGE PIECE_PACK IS
  PROCEDURE TO_DISPLAY(DP_ID NUMBER,DP_NAME VARCHAR2,DP_COST NUMBER,DA_ID NUMBER,DB_ID NUMBER,DB_ON DATE);
  FUNCTION EXP_PIECE RETURN NUMBER;
  FUNCTION NAME RETURN VARCHAR2;
END PIECE_PACK;
  