'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.1433
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace ServiceReference1
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="ServiceReference1.ServiceSoap")>  _
    Public Interface ServiceSoap
        
        'CODEGEN: Generating message contract since element name str from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Count_Vowels", ReplyAction:="*")>  _
        Function Count_Vowels(ByVal request As ServiceReference1.Count_VowelsRequest) As ServiceReference1.Count_VowelsResponse
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class Count_VowelsRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="Count_Vowels", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As ServiceReference1.Count_VowelsRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ServiceReference1.Count_VowelsRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class Count_VowelsRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public str As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal str As String)
            MyBase.New
            Me.str = str
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class Count_VowelsResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="Count_VowelsResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As ServiceReference1.Count_VowelsResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ServiceReference1.Count_VowelsResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class Count_VowelsResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public Count_VowelsResult As Integer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Count_VowelsResult As Integer)
            MyBase.New
            Me.Count_VowelsResult = Count_VowelsResult
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")>  _
    Public Interface ServiceSoapChannel
        Inherits ServiceReference1.ServiceSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")>  _
    Partial Public Class ServiceSoapClient
        Inherits System.ServiceModel.ClientBase(Of ServiceReference1.ServiceSoap)
        Implements ServiceReference1.ServiceSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceReference1_ServiceSoap_Count_Vowels(ByVal request As ServiceReference1.Count_VowelsRequest) As ServiceReference1.Count_VowelsResponse Implements ServiceReference1.ServiceSoap.Count_Vowels
            Return MyBase.Channel.Count_Vowels(request)
        End Function
        
        Public Function Count_Vowels(ByVal str As String) As Integer
            Dim inValue As ServiceReference1.Count_VowelsRequest = New ServiceReference1.Count_VowelsRequest
            inValue.Body = New ServiceReference1.Count_VowelsRequestBody
            inValue.Body.str = str
            Dim retVal As ServiceReference1.Count_VowelsResponse = CType(Me,ServiceReference1.ServiceSoap).Count_Vowels(inValue)
            Return retVal.Body.Count_VowelsResult
        End Function
    End Class
End Namespace
